name: Test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
          run_install: |
            - args: [--frozen-lockfile]
      - name: Run tests
        run: pnpm test
